#
# Makefile for misc devices that really don't fit anywhere else.
#
include $(srctree)/drivers/misc/mediatek/Makefile.custom
# obj-y += hct_nt35521s_dsi_vdo_hd_boe_50_xld/hct_nt35521s_dsi_vdo_hd_boe_50_xld.o
