#
LOCAL_DIR := $(GET_LOCAL_DIR)
TARGET := qinf21pro
MODULES += app/mt_boot \
           dev/lcm
MTK_EMMC_SUPPORT = yes
MTK_MMC_COMBO_DRV = yes
MTK_EMMC_SUPPORT_OTP = yes
MTK_SMI_SUPPORT = yes
MTK_KERNEL_POWER_OFF_CHARGING = yes
DEFINES += MTK_NEW_COMBO_EMMC_SUPPORT
DEFINES += MTK_GPT_SCHEME_SUPPORT
MTK_CHARGER_NEW_ARCH := yes
MTK_PUMP_EXPRESS_PLUS_SUPPORT := yes
MTK_MT6370_PMU_CHARGER_SUPPORT := yes
MTK_MT6370_PMU_BLED_SUPPORT := yes
MTK_CHARGER_INTERFACE := yes
MTK_LCM_PHYSICAL_ROTATION = 0
CUSTOM_LK_LCM="nt35695B_fhd_dsi_vdo_auo_rt5081"
DEFINES += MTK_ROUND_CORNER_SUPPORT
MTK_SECURITY_SW_SUPPORT = yes
MTK_VERIFIED_BOOT_SUPPORT = yes
MTK_SEC_FASTBOOT_UNLOCK_SUPPORT = yes
SPM_FW_USE_PARTITION = yes
BOOT_LOGO := hd720
DEFINES += MTK_LCM_PHYSICAL_ROTATION_HW
DEBUG := 2
CUSTOM_LK_USB_UNIQUE_SERIAL=yes
MTK_TINYSYS_SCP_SUPPORT = yes
MTK_TINYSYS_SSPM_SUPPORT = yes
DEFINES += NO_POWER_OFF=y
#DEFINES += FPGA_BOOT_FROM_LK=y
MTK_PROTOCOL1_RAT_CONFIG = C/Lf/Lt/W/T/G
MTK_GOOGLE_TRUSTY_SUPPORT = no
DEFINES += MTK_MT6370_PMU
MTK_EFUSE_WRITER_SUPPORT = no
MTK_SMC_ID_MGMT = yes
DEVELOP_STAGE = SB
MTK_MT22_MODE :=H2
MTK_DYNAMIC_CCB_BUFFER_GEAR_ID =
DEFINES += RECOVERY_AS_BOOT
MTK_AB_OTA_UPDATER += yes